# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Multitap' do
 
pod 'Parse'
pod 'MXSqlite'

end

target 'MultitapTests' do

end

target 'MultitapUITests' do

end

